substitutions:
  name: esp32-s3-box-3-99f6e0
  friendly_name: Bedroom Box Assistant
packages:
  esphome.voice-assistant: github://esphome/wake-word-voice-assistants/esp32-s3-box-3/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: iKI6ofv2a/cznRBxyVrKuIwnWuIxXrz6FH3WLj9/2ac=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password