substitutions:
  name: office-atom-echo
  friendly_name: Office Atom Echo

packages:
  m5stack.atom-echo-wake-word-voice-assistant: github://esphome/wake-word-voice-assistants/m5stack-atom-echo/m5stack-atom-echo.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: ddGgODlEL9L/jHR5YFkM10XAZL/dRSTKyFX/OwsOx3E=


wifi:
  manual_ip:
    static_ip: 192.168.20.131
    gateway: 192.168.20.1
    subnet: 255.255.255.0
  ssid: !secret wifi_ssid
  password: !secret wifi_password